import {useDispatch} from "react-redux";
import {useEffect, useState} from "react";
import {set_pathname} from "../../../root/commonSlice";
import Head from "next/head";
import styles from "../../../styles/Home.module.css";
import ActiveLink from "../../../root/router";

function Loaded({setPathname}: any) {
  const dispatch = useDispatch()
  useEffect(() => {
    const pathname = window.location.pathname
    setPathname(pathname)
    dispatch(set_pathname(pathname))
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [window.location.pathname])
  return null
}

function Posts() {
  const [pathname, setPathname] = useState("")
  const [isLoaded, setIsLoaded] = useState(false)
  const dispatch = useDispatch()

  useEffect(() => {
    if (window) {
      const pathname = window.location.pathname
      setPathname(pathname)
      dispatch(set_pathname(pathname))
      setIsLoaded(true)
    }
  }, [dispatch])

  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app"/>
    </Head>

    <main className={styles.main}>
      {isLoaded && <Loaded setPathname={setPathname}/>}
      This is {pathname}
      <br/>
      <br/>
      <ActiveLink href={"/about"}>
        <button>about</button>
      </ActiveLink>
      <br/>
      <ActiveLink href={"/"}>
        <button>home</button>
      </ActiveLink>
      <br/>
      <ActiveLink href={"/blog"}>
        <button>/blog</button>
      </ActiveLink>
      <br/>
      <ActiveLink href={"/blog/categories"}>
        <button>/blog/categories</button>
      </ActiveLink>
      <br/>
      <ActiveLink href={"/blog/category/1234"}>
        <button>/blog/category/1234</button>
      </ActiveLink>
      <br/>
      <ActiveLink href={"/blog/post/5678"}>
        <button>/blog/post/5678</button>
      </ActiveLink>
    </main>
  </>
}

export default Posts
