import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ActiveLink from "../root/router";
import {useDispatch, useSelector} from "react-redux";
import {data_list, set_pathname} from "../root/commonSlice";
import {useEffect, useState} from "react";

export default function Home() {
  const dispatch = useDispatch()
  const [dataList, setDataList] = useState({})
  const data = useSelector(data_list)
  useEffect(() => {
    dispatch(set_pathname("/"))
  }, [dispatch])

  useEffect(() => {
    if (data) {
      setDataList(data)
    }
  }, [data])

  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app"/>
    </Head>

    <main className={styles.main}>
      This is home
      <br/>
      <br/>
      <a href={"/api"} style={{color: "#0dd"}}>/api</a>
      <a href={"/api/users/login"}
         style={{color: "red"}}>/api/users/login</a>
      <br/>
      <ActiveLink href={"/about"}>
        <button>about</button>
      </ActiveLink>
      <br/>
      <ActiveLink href={"/blog"}>
        <button>/blog</button>
      </ActiveLink>
      <br/>
      <ActiveLink href={"/blog/categories"}>
        <button>/blog/categories</button>
      </ActiveLink>
      <br/>
      <ActiveLink href={"/blog/category/1234"}>
        <button>/blog/category/1234</button>
      </ActiveLink>
      <br/>
      <ActiveLink href={"/blog/post/5678"}>
        <button>/blog/post/5678</button>
      </ActiveLink>
      <br/>
      common.data_list : {JSON.stringify(dataList)}
      <br/>
      <br/>
      <button onClick={() => {
        dispatch({type: "SAGA_GET_DATA_LIST", url: "/api/users/login"})
      }}>saga /api/users/login
      </button>
      <br/>
      <button onClick={() => {
        dispatch({type: "SAGA_GET_DATA_LIST", url: "/api"})
      }}>saga /api
      </button>
    </main>
  </>
}
